[target.xtensa-esp32-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor"

[env]
MCU = "esp32"
ESP_IDF_VERSION = "v5.3"
ESP_LOG = "debug"

[build]
target = "xtensa-esp32-espidf"

[unstable]
build-std = ["std", "panic_abort"]

[alias]
erase-nvs = "espflash erase-region 0x9000 0x6000"
